/*
 * generated by Xtext 2.17.0
 */
package quickGUI


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class QuickGUIStandaloneSetup extends QuickGUIStandaloneSetupGenerated {

	def static void doSetup() {
		new QuickGUIStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
