/**
 * generated by Xtext 2.17.0
 */
package quickGUI.quickGUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Horizontal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see quickGUI.quickGUI.QuickGUIPackage#getHorizontal()
 * @model
 * @generated
 */
public interface Horizontal extends Layout
{
} // Horizontal
