/**
 * generated by Xtext 2.17.0
 */
package quickGUI.quickGUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Box</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link quickGUI.quickGUI.InputBox#getRequireCheck <em>Require Check</em>}</li>
 * </ul>
 *
 * @see quickGUI.quickGUI.QuickGUIPackage#getInputBox()
 * @model
 * @generated
 */
public interface InputBox extends Element
{
  /**
   * Returns the value of the '<em><b>Require Check</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Require Check</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Require Check</em>' attribute.
   * @see #setRequireCheck(String)
   * @see quickGUI.quickGUI.QuickGUIPackage#getInputBox_RequireCheck()
   * @model
   * @generated
   */
  String getRequireCheck();

  /**
   * Sets the value of the '{@link quickGUI.quickGUI.InputBox#getRequireCheck <em>Require Check</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Require Check</em>' attribute.
   * @see #getRequireCheck()
   * @generated
   */
  void setRequireCheck(String value);

} // InputBox
