/**
 * generated by Xtext 2.17.0
 */
package quickGUI.quickGUI;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Layout</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link quickGUI.quickGUI.Layout#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see quickGUI.quickGUI.QuickGUIPackage#getLayout()
 * @model
 * @generated
 */
public interface Layout extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link quickGUI.quickGUI.Element}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see quickGUI.quickGUI.QuickGUIPackage#getLayout_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElements();

} // Layout
