/**
 * generated by Xtext 2.17.0
 */
package quickGUI.quickGUI;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see quickGUI.quickGUI.QuickGUIFactory
 * @model kind="package"
 * @generated
 */
public interface QuickGUIPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "quickGUI";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.QuickGUI.quickGUI";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "quickGUI";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QuickGUIPackage eINSTANCE = quickGUI.quickGUI.impl.QuickGUIPackageImpl.init();

  /**
   * The meta object id for the '{@link quickGUI.quickGUI.impl.GUIImpl <em>GUI</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see quickGUI.quickGUI.impl.GUIImpl
   * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getGUI()
   * @generated
   */
  int GUI = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI__TITLE = 0;

  /**
   * The feature id for the '<em><b>Layout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI__LAYOUT = 1;

  /**
   * The number of structural features of the '<em>GUI</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link quickGUI.quickGUI.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see quickGUI.quickGUI.impl.ElementImpl
   * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link quickGUI.quickGUI.impl.LayoutImpl <em>Layout</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see quickGUI.quickGUI.impl.LayoutImpl
   * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getLayout()
   * @generated
   */
  int LAYOUT = 2;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Layout</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link quickGUI.quickGUI.impl.HorizontalImpl <em>Horizontal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see quickGUI.quickGUI.impl.HorizontalImpl
   * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getHorizontal()
   * @generated
   */
  int HORIZONTAL = 3;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HORIZONTAL__ELEMENTS = LAYOUT__ELEMENTS;

  /**
   * The number of structural features of the '<em>Horizontal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HORIZONTAL_FEATURE_COUNT = LAYOUT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link quickGUI.quickGUI.impl.VerticalImpl <em>Vertical</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see quickGUI.quickGUI.impl.VerticalImpl
   * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getVertical()
   * @generated
   */
  int VERTICAL = 4;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTICAL__ELEMENTS = LAYOUT__ELEMENTS;

  /**
   * The number of structural features of the '<em>Vertical</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTICAL_FEATURE_COUNT = LAYOUT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link quickGUI.quickGUI.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see quickGUI.quickGUI.impl.ButtonImpl
   * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getButton()
   * @generated
   */
  int BUTTON = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__NAME = ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link quickGUI.quickGUI.impl.TextBoxImpl <em>Text Box</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see quickGUI.quickGUI.impl.TextBoxImpl
   * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getTextBox()
   * @generated
   */
  int TEXT_BOX = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_BOX__NAME = ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Text Box</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_BOX_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link quickGUI.quickGUI.GUI <em>GUI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GUI</em>'.
   * @see quickGUI.quickGUI.GUI
   * @generated
   */
  EClass getGUI();

  /**
   * Returns the meta object for the attribute '{@link quickGUI.quickGUI.GUI#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see quickGUI.quickGUI.GUI#getTitle()
   * @see #getGUI()
   * @generated
   */
  EAttribute getGUI_Title();

  /**
   * Returns the meta object for the containment reference '{@link quickGUI.quickGUI.GUI#getLayout <em>Layout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Layout</em>'.
   * @see quickGUI.quickGUI.GUI#getLayout()
   * @see #getGUI()
   * @generated
   */
  EReference getGUI_Layout();

  /**
   * Returns the meta object for class '{@link quickGUI.quickGUI.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see quickGUI.quickGUI.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link quickGUI.quickGUI.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see quickGUI.quickGUI.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link quickGUI.quickGUI.Layout <em>Layout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout</em>'.
   * @see quickGUI.quickGUI.Layout
   * @generated
   */
  EClass getLayout();

  /**
   * Returns the meta object for the containment reference list '{@link quickGUI.quickGUI.Layout#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see quickGUI.quickGUI.Layout#getElements()
   * @see #getLayout()
   * @generated
   */
  EReference getLayout_Elements();

  /**
   * Returns the meta object for class '{@link quickGUI.quickGUI.Horizontal <em>Horizontal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Horizontal</em>'.
   * @see quickGUI.quickGUI.Horizontal
   * @generated
   */
  EClass getHorizontal();

  /**
   * Returns the meta object for class '{@link quickGUI.quickGUI.Vertical <em>Vertical</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertical</em>'.
   * @see quickGUI.quickGUI.Vertical
   * @generated
   */
  EClass getVertical();

  /**
   * Returns the meta object for class '{@link quickGUI.quickGUI.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see quickGUI.quickGUI.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for class '{@link quickGUI.quickGUI.TextBox <em>Text Box</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Box</em>'.
   * @see quickGUI.quickGUI.TextBox
   * @generated
   */
  EClass getTextBox();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  QuickGUIFactory getQuickGUIFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link quickGUI.quickGUI.impl.GUIImpl <em>GUI</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see quickGUI.quickGUI.impl.GUIImpl
     * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getGUI()
     * @generated
     */
    EClass GUI = eINSTANCE.getGUI();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GUI__TITLE = eINSTANCE.getGUI_Title();

    /**
     * The meta object literal for the '<em><b>Layout</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GUI__LAYOUT = eINSTANCE.getGUI_Layout();

    /**
     * The meta object literal for the '{@link quickGUI.quickGUI.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see quickGUI.quickGUI.impl.ElementImpl
     * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link quickGUI.quickGUI.impl.LayoutImpl <em>Layout</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see quickGUI.quickGUI.impl.LayoutImpl
     * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getLayout()
     * @generated
     */
    EClass LAYOUT = eINSTANCE.getLayout();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT__ELEMENTS = eINSTANCE.getLayout_Elements();

    /**
     * The meta object literal for the '{@link quickGUI.quickGUI.impl.HorizontalImpl <em>Horizontal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see quickGUI.quickGUI.impl.HorizontalImpl
     * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getHorizontal()
     * @generated
     */
    EClass HORIZONTAL = eINSTANCE.getHorizontal();

    /**
     * The meta object literal for the '{@link quickGUI.quickGUI.impl.VerticalImpl <em>Vertical</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see quickGUI.quickGUI.impl.VerticalImpl
     * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getVertical()
     * @generated
     */
    EClass VERTICAL = eINSTANCE.getVertical();

    /**
     * The meta object literal for the '{@link quickGUI.quickGUI.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see quickGUI.quickGUI.impl.ButtonImpl
     * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '{@link quickGUI.quickGUI.impl.TextBoxImpl <em>Text Box</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see quickGUI.quickGUI.impl.TextBoxImpl
     * @see quickGUI.quickGUI.impl.QuickGUIPackageImpl#getTextBox()
     * @generated
     */
    EClass TEXT_BOX = eINSTANCE.getTextBox();

  }

} //QuickGUIPackage
