/**
 * generated by Xtext 2.17.0
 */
package quickGUI.quickGUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text Box</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see quickGUI.quickGUI.QuickGUIPackage#getTextBox()
 * @model
 * @generated
 */
public interface TextBox extends Element
{
} // TextBox
