/**
 * generated by Xtext 2.17.0
 */
package quickGUI.quickGUI.impl;

import org.eclipse.emf.ecore.EClass;

import quickGUI.quickGUI.Button;
import quickGUI.quickGUI.QuickGUIPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Button</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ButtonImpl extends ElementImpl implements Button
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ButtonImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QuickGUIPackage.Literals.BUTTON;
  }

} //ButtonImpl
