/**
 * generated by Xtext 2.17.0
 */
package quickGUI.quickGUI.impl;

import org.eclipse.emf.ecore.EClass;

import quickGUI.quickGUI.Horizontal;
import quickGUI.quickGUI.QuickGUIPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Horizontal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class HorizontalImpl extends LayoutImpl implements Horizontal
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HorizontalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QuickGUIPackage.Literals.HORIZONTAL;
  }

} //HorizontalImpl
