/**
 * generated by Xtext 2.17.0
 */
package quickGUI.quickGUI.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import quickGUI.quickGUI.InputBox;
import quickGUI.quickGUI.QuickGUIPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Input Box</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link quickGUI.quickGUI.impl.InputBoxImpl#getRequireCheck <em>Require Check</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InputBoxImpl extends ElementImpl implements InputBox
{
  /**
   * The default value of the '{@link #getRequireCheck() <em>Require Check</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequireCheck()
   * @generated
   * @ordered
   */
  protected static final String REQUIRE_CHECK_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRequireCheck() <em>Require Check</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequireCheck()
   * @generated
   * @ordered
   */
  protected String requireCheck = REQUIRE_CHECK_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InputBoxImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QuickGUIPackage.Literals.INPUT_BOX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRequireCheck()
  {
    return requireCheck;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRequireCheck(String newRequireCheck)
  {
    String oldRequireCheck = requireCheck;
    requireCheck = newRequireCheck;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QuickGUIPackage.INPUT_BOX__REQUIRE_CHECK, oldRequireCheck, requireCheck));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QuickGUIPackage.INPUT_BOX__REQUIRE_CHECK:
        return getRequireCheck();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QuickGUIPackage.INPUT_BOX__REQUIRE_CHECK:
        setRequireCheck((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QuickGUIPackage.INPUT_BOX__REQUIRE_CHECK:
        setRequireCheck(REQUIRE_CHECK_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QuickGUIPackage.INPUT_BOX__REQUIRE_CHECK:
        return REQUIRE_CHECK_EDEFAULT == null ? requireCheck != null : !REQUIRE_CHECK_EDEFAULT.equals(requireCheck);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (requireCheck: ");
    result.append(requireCheck);
    result.append(')');
    return result.toString();
  }

} //InputBoxImpl
