/**
 * generated by Xtext 2.17.0
 */
package quickGUI.quickGUI.impl;

import org.eclipse.emf.ecore.EClass;

import quickGUI.quickGUI.QuickGUIPackage;
import quickGUI.quickGUI.TextBox;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Text Box</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TextBoxImpl extends ElementImpl implements TextBox
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TextBoxImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QuickGUIPackage.Literals.TEXT_BOX;
  }

} //TextBoxImpl
