/**
 * generated by Xtext 2.17.0
 */
package quickGUI.quickGUI.impl;

import org.eclipse.emf.ecore.EClass;

import quickGUI.quickGUI.QuickGUIPackage;
import quickGUI.quickGUI.Vertical;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Vertical</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VerticalImpl extends LayoutImpl implements Vertical
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VerticalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QuickGUIPackage.Literals.VERTICAL;
  }

} //VerticalImpl
