/*
 * generated by Xtext 2.17.0
 */
package quickGUI.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQuickGUIScopeProvider extends DelegatingScopeProvider {
}
