/*
 * generated by Xtext 2.17.0
 */
package quickGUI.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractQuickGUIValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(quickGUI.quickGUI.QuickGUIPackage.eINSTANCE);
		return result;
	}
}
